# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ji You's jekyll-firebase-comments Demo
email: jiyou.linux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ji You's demo site for jekyll-firebase-comments.
  Jekyll default setting and style is used.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jithee.name/jekyll-firebase-comments/" # the base hostname & protocol for your site
twitter_username: nightghostjiyou
github_username:  JiYouMCC

# Build settings
markdown: kramdown
